name: taskaty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  date_picker_timeline: ^1.2.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.0.0
  flutter_timezone: ^4.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  lottie: ^3.3.1
  timezone: ^0.10.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: normal
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  assets:
    - assets/images/
    - assets/icons/
  uses-material-design: true
